### ISSUE TITLE
game crashes upon initialization: NoClassDefFoundError with autoconfig data

### ISSUE THREAD

**Issue by limistonya** [ChristopherHaws/mc-text-utilities#73]
the game crashes upon startup. i double checked the dependencies and they are in the mods folder. im on 1.19.3
the list of possibly relevant mods are:
- autoconfig 3.4.0
- cloth api 4.0.65
- cloth config 9.0.94
- fabric api 0.73.0
- indium 1.0.12
- modmenu 5.0.2
- sodium 0.4.8 build 22
- text utilities 1.4.1
there are others but i wouldnt believe they affect initialization like this

> Description: Initializing game
> 
> java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'textutilities'!
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
> 	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
> 	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
> 	at net.minecraft.class_310.<init>(class_310.java:465)
> 	at net.minecraft.client.main.Main.method_44604(Main.java:205)
> 	at net.minecraft.client.main.Main.main(Main.java:51)
> 	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
> 	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
> Caused by: java.lang.NoClassDefFoundError: me/shedaniel/autoconfig/ConfigData
> 	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
> 	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1012)
> 	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:153)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at io.chaws.textutilities.TextUtilities.onInitialize(TextUtilities.java:22)
> 	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
> 	... 8 more
> Caused by: java.lang.ClassNotFoundException: me.shedaniel.autoconfig.ConfigData
> 	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
> 	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112)
> 	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
> 	... 18 more

**Comment by limistonya** [comment]
update: game also crashes when i remove text utilities. but this time the crash is due to cloth things and has a different error code. game loads properly when both mods are removed.
